---
- name: Start Sabnzbd
  block:
    - name: Create Sabnzbd Data Directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ sabnzbd_data_directory }}"
        - "{{ sabnzbd_downloads_directory }}/tv"
        - "{{ sabnzbd_downloads_directory }}/movies"
        - "{{ sabnzbd_downloads_directory }}/incomplete"
        - "{{ fasttemp_root }}/sabnzbd"

    - name: Sabnzbd
      community.docker.docker_container:
        name: "{{ sabnzbd_container_name }}"
        image: "{{ sabnzbd_image_name }}:{{ sabnzbd_image_version }}"
        pull: true
        volumes:
          - "{{ sabnzbd_data_directory }}:/config:rw"
          - "{{ sabnzbd_downloads_directory }}:/downloads:rw"
          - "{{ plex_sports_directory }}:/sports:rw"
          - "{{ fasttemp_root }}/sabnzbd:/fasttemp:rw"
        ports:
          - "{{ sabnzbd_port }}:8080"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ sabnzbd_user_id }}"
          PGID: "{{ sabnzbd_group_id }}"
        restart_policy: unless-stopped
        labels:
          traefik.enable: "{{ sabnzbd_available_externally | string }}"
          traefik.http.routers.sabnzbd.rule: "Host(`{{ sabnzbd_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.sabnzbd.tls.certresolver: "letsencrypt"
          traefik.http.routers.sabnzbd.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.sabnzbd.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.routers.sabnzbd.middlewares: "sabnzbdwhitelist"
          traefik.http.services.sabnzbd.loadbalancer.server.port: "8080"
          traefik.http.middlewares.sabnzbdwhitelist.ipallowlist.sourcerange: "{{ private_whitelist }}"
  when: sabnzbd_enabled is true

- name: Stop Sabnzbd
  block:
    - name: Stop Sabnzbd
      community.docker.docker_container:
        name: "{{ sabnzbd_container_name }}"
        state: absent
  when: sabnzbd_enabled is false
